services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: dartsguesser_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=jdGCQXPpLyv8g6cm4HDFzSKA
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=4493abcd
      - MYSQL_DB=dartsguesser
    depends_on:
      - db
    networks:
      - dartsguesser_network

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: dartsguesser_scraper
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=4493abcd
      - MYSQL_DB=dartsguesser
    volumes:
      - .:/app
    restart: always
    shm_size: 4g
    depends_on:
      - db
    networks:
      - dartsguesser_network

  db:
    image: mysql:8.0
    container_name: dartsguesser_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4493abcd
      MYSQL_DATABASE: dartsguesser
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dartsguesser_network

volumes:
  db_data:

networks:
  dartsguesser_network:
    driver: bridge
